# Site settings
title: Hong Kong
description:
baseurl: "/hong-kong" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, bower_components, bower.json, README.md, npm-debug.log]
